[project]
name = "adventure-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==5.2",
    "django-debug-toolbar>=6.1.0",
    "google-genai>=1.59.0",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.2.1",
]
